spring.application.name=organiser
server.port=5000
server.servlet.context-path=/api/v1

# Active Profile
spring.profiles.active=${ACTIVE_PROFILE:local}

# JWT Configuration
jwt.secret=${JWT_SECRET:jwt-secret}
jwt.access-token.expiration=7200000
jwt.refresh-token.expiration=86400000

# Logging Configuration
logging.level.root=INFO
logging.level.interview.organiser=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Pagination
spring.data.web.pageable.default-page-size=5
spring.data.web.pageable.max-page-size=100

# AWS S3 Configuration (Fill in your credentials)
aws.s3.access-key=${AWS_S3_ACCESS_KEY:access-key}
aws.s3.secret-key=${AWS_S3_SECRET_KEY:secret-key}
aws.s3.region=${AWS_S3_REGION:ap-south-1}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:interview-organiser}
aws.s3.presigned-url-expiration=3600

# Notification Configuration
notification.read-retention-days=30
notification.cleanup.cron=0 0 2 * * ?

# MongoDB Configuration
spring.data.mongodb.uri=${MONGO_DB_URI:mongodb://localhost:27017/interview}
spring.data.mongodb.auto-index-creation=true